"""atualizando o modelo

Revision ID: 41cb9351bbd2
Revises: 7fe7e8d14423
Create Date: 2025-11-19 12:34:32.082432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41cb9351bbd2'
down_revision: Union[str, Sequence[str], None] = '7fe7e8d14423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prognosticos', sa.Column('previsao', sa.String(), nullable=False))
    op.drop_column('prognosticos', 'resultado')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prognosticos', sa.Column('resultado', sa.VARCHAR(), nullable=False))
    op.drop_column('prognosticos', 'previsao')
    # ### end Alembic commands ###
