"""iniciando migracao

Revision ID: 7fe7e8d14423
Revises: 
Create Date: 2025-11-17 17:30:39.470400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe7e8d14423'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('prognosticos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipa_casa', sa.String(), nullable=False),
    sa.Column('equipa_fora', sa.String(), nullable=False),
    sa.Column('resultado', sa.String(), nullable=False),
    sa.Column('data_jogo', sa.DateTime(), nullable=False),
    sa.Column('plano', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('prognosticos_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('plano', sa.String(), nullable=True),
    sa.Column('data_expiracao_plano', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_pagamento', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('prognosticos')
    op.drop_table('planos')
    # ### end Alembic commands ###
