"""atualizando o modelo

Revision ID: dd988f87f192
Revises: de685e2a9ab6
Create Date: 2025-11-24 14:23:40.421257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd988f87f192'
down_revision: Union[str, Sequence[str], None] = 'de685e2a9ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prognosticos', 'mensagem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prognosticos', sa.Column('mensagem', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
