"""atualizando o modelo

Revision ID: de685e2a9ab6
Revises: 3860b90a80a2
Create Date: 2025-11-23 13:51:04.138671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de685e2a9ab6'
down_revision: Union[str, Sequence[str], None] = '3860b90a80a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prognosticos', sa.Column('mensagem', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prognosticos', 'mensagem')
    # ### end Alembic commands ###
